### ISSUE TITLE
Update to python3

### ISSUE THREAD

**Issue by atombaby** [FredHutch/scicomp-leftover#1]
This was originally written in the good ol' days of python2... it's not working in the python3 world, particularly the `subprocess` calls.

**Comment by chrisequalsdev** [comment]
I started looking at this. Looks like this will fix most of the issues. I'll work on it some more.

```python
# Python2
result = subprocess.check_output(cmd, stderr=subprocess.STDOUT)

# Python3
result = subprocess.run(cmd, stdout=subprocess.PIPE, universal_newlines=True, check=True).stdout
```
